apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: springboot-blue
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: springboot
        version: "v1"
    spec:
      containers:
        - name: springboot
          image: 'yash4993/app'
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /devops/skills
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: springboot
  labels:
    name: springboot
    version: "v1"
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot
    version: "v1"
  type: LoadBalancer

